- lib/fs/index.js
- lib/index.js
- lib/rest/index.js
- tests/test_fs.js
- tests/test_rest.js
The linter asked me to break files into one class per file. I like that so I did it. However, it makes importing more difficult for users. I created an `index.js` to collect all the "public" objects into the root namespace...
```node
const Client = require('rest/client');
const BasicClient = require('rest/basic');
//is now:
const { Client, BasicClient } = require('smartfile');
```
> Make importing easier for users.

- lib/fs/filesystem.js
@cabarnes I decided to add metrics to some of the high-level calls too. I had omitted them at first because they don't map directly to API calls, but some like `open()` and `close()` do read and write files. If for no other reason it would be nice to see how often they are called.
My goal with these metrics is to report them along with the service level metrics in `ftpd`, `sftpd`, and `davd`. I want to give visibility into their performance.
I did omit `fstat()` because it just forwards to `stat()` which has metrics.
> Add metrics for higher-level calls.

- index.js
- lib/fs/filesystem.js
- tests/test_fs.js
Simple change I forgot. This will allow simple import like:
`const { metrics } = require('smartfile');`
> Export metrics from package root.

- lib/fs/filesystem.js
- lib/rest/client.js
Was causing errors when listing an empty directory.
> Return empty array, not null for empty directory.

- lib/rest/client.js
Make the metric names a bit clearer.
> Rename rest client metrics.

- lib/rest/client.js
Celery jobs are not running in a timely manner within my local instance. If a delete is started over FTP, the FTP client eventually times out, but the FTP server, due to how polling is set up will continue polling the operation forever.
This PR puts an upper bounds on how long a job will be polled. I increased the time to the first poll (when hitting beta, about half the operations were still running on the first poll, requiring a second poll).  This should hopefully ensure the task is done by the time of first poll. I also changed backoff increase to exponential up to a max of 6 seconds.
> Don't poll forever.

- lib/fs/fileproxy.js
- lib/fs/filesystem.js
- lib/rest/basic.js
- lib/rest/client.js
- package-lock.json
- package.json
- tests/test_auth.js
- tests/test_fs.js
- tests/test_rest.js
- tests/utils.js
The library I was using for HTTP is deprecated. Node has http / https libraries included. They are lower-level and afford more control over the requests (which is nice because I am unable to do some things I would like in dependent projects).
This PR removes the request library and replaces it's functionality with a new function `request()` that handles all the HTTP particulars.
> Remove deprecated request lib.

- lib/rest/client.js
- package-lock.json
- package.json
- tests/test_rest.js
Allows uploading non-ascii filename.
Closes https://github.com/smartfile/client-node/issues/34
> Allow upload of non-ascii filenames.

- lib/fs/fileproxy.js
- lib/fs/filesystem.js
- tests/test_fs.js
- tests/test_rest.js
I modified all `filesystem` operations that receive file objects from the API so that they add these objects to cache. I added assertions in the unit tests to ensure objects exist in cache. I had to modify the mock JSON to include `name` and `path` attributes where appropriate (as these are necessary for caching).
> Add more caching.

- lib/fs/filesystem.js
- lib/rest/client.js
- tests/test_rest.js
This one will allow headers needed for range requests and audit events etc.
> Allow overriding HTTP options (including headers).

- lib/fs/filesystem.js
I want access to the request object used for by `createReadStream()` so I can `abort()` it. The download data flows over a response stream provided by the callback, but the request object is useful for managing the overall request.
> Rename some vars, return request obj from download().

- tests/test_auth.js
- tests/test_fs.js
Closes #47 
Adds tests for authentication failing and when `null` is passed as `options`
> Add tests for failures found upstream

- lib/keys.js
- lib/rest/client.js
- tests/test_keys.js
This PR makes a few small changes to the API client.
- The trailing slash after key name bothered me so I removed it. The slash after username is still necessary.
- PUT method is now used to create AND update keys. This means we save a round-trip to check if something exists before saving it.
- I added caching for keys, this benefits downstream in several ways, I am able to remove some caching. Round trips are reduced.
- Deep copy global options when making an HTTP request so that they are not polluted.
> Key API updates and bug fixes.

- lib/rest/client.js
The metric label `endpoint` included path (which is actually an argument). This produces a wide variety of `endpoint` labels, disallowing graphs by `endpoint`. This PR separates them until the request is performed.
> HTTP_REQUEST metric endpoint label.

- lib/fs/filesystem.js
Caching the error returned by the rest client can causes problems downstream. The error holds references to the http request and response and can contain circular references. There is no reason to use the original error (or an actual error object at all really) so just create a new one.
> Use new error, original error references req/res.

- lib/rest/client.js
I was looking into this open (at the time) issue: https://github.com/smartfile/client-node/issues/57
It is apparently fixed (with a test case) but I found other issues with path handling on the URI and fixed those.
> Always URI encode paths on URI.

- lib/fs/filesystem.js
- lib/rest/client.js
Don't blindly access `result.result` attribute in API response.
Fixes https://github.com/smartfile/client-node/issues/59
> Result.result

- lib/fs/filesystem.js
Revert this, it is not necessary (and in fact emits two events).
> This did not work as planned.

- lib/fs/filesystem.js
During a move or copy, the following can occur:
- Client checks destination before move / copy. Destination does not exist and populates cache with 404 Error.
- Client performs move / copy operation.
- Client reads destination information but receives cached 404 result.
This PR addresses this by evicting the destination from cache before performing the move / copy operation.
> Move / copy cache eviction.

- lib/rest/client.js
I am now (ab)using the fact that some API client methods return the request object. This affords the opportunity to modify parameters of the request such as the method and URL. When this is done, the logging statement does not reflect these changes as it logged from the options object rather than directly from the request object. This PR addresses that.
Additionally, some of the options used during upload were inconsistent. For one, the timeout was not disabled for PATCH method and also PATCH method sent an additional header that is no longer necessary.
> Better logging. Consistent upload options.

- lib/rest/basic.js
- lib/rest/client.js
- package-lock.json
- package.json
- tests/test_auth.js
This PR adds general cookie handling. Callers can add cookies to the client: `client.cookies.setCookie(...)` etc. Also, cookies from the server are preserved and sent with future requests.
Cookie handling is used to implement `login()` and `logout()` methods which start and stop a session. When a session is started, the `sessionid` and `csrftoken` cookies will be sent with each request. Any authentication is disabled while the session is active. On `logout()` the `sessionid` and `csrftoken` cookies are removed and authentication is re-enabled.
Also, the CSRF token is sent via header for HTTP verbs that possibly mutate data. CSRF is required while session authentication is being used.
> Add session support to API client.

- lib/rest/client.js
- package-lock.json
- package.json
- tests/test_auth.js
I renamed these because when using authentication as provided by `BasicClient`, every request is authenticated. This set of functions effectively switch to session authentication and back again, they do not toggle authentication wholly.
> Better names for these functions.

- lib/rest/client.js
An array object will always be truthy. The length must be checked to determine if it is empty
> Array length must be evaluated to determine empty array

- lib/rest/client.js
Cookies were not matching because the `path` is always `/` and the `secure` flag is always set.
The `auth` part of options should only be set by the `authenticate` implementation
> Fix cookie handling

- lib/fs/filesystem.js
- lib/rest/client.js
- tests/test_fs.js
- tests/test_rest.js
During a directory listing, use `setImmediate()` to fetch the next page of results in parallel with the callback for the current page of results.
Obviously these won't strictly run in parallel, but the fetch should be started, and once the first callback in that execution path is encountered, execution will yield, allowing the current page callback to execute.
In other words, the HTTP request should be in-flight while the current page is being rendered to the caller.
I also reduced the page size to 100, since that is the hard max on the server side.
> Fetch next page of results in parallel with callback.

- Makefile
- lib/fs/filesystem.js
- lib/rest/client.js
- package-lock.json
- package.json
- tests/test_fs.js
Options from caller were ignored within `readdirstats()`. This change allows the caller to choose page limit etc.
I also reduced some of the logging output (silly level) and added some information to some log messages.
> Don't clobber user-supplied options.

- lib/rest/client.js
- tests/test_fs.js
The lua upload handler prevents upload errors from being reflected in the HTTP status code. Instead the API client must inspect the JSON returned from the API to detect an error.
https://github.com/btimby/nginx-lua-chunkedup/issues/15
This will get the http status code if available. The lua chunkedup module will provide it:
https://github.com/btimby/nginx-lua-chunkedup/pull/16
> Upload error handling.

- lib/fs/filesystem.js
- lib/rest/client.js
- tests/test_fs.js
- tests/test_rest.js
Uses the query parameter `fields` to request a limited set of fields for directory listings
> Support limited fields for directory listings

- lib/rest/client.js
- tests/test_auth.js
Django requires a referer header for CSRF validation when making a secure connection. CSRF is required when doing session authentication.
> Send a referer header for CSRF validation.

- lib/fs/filesystem.js
- lib/keys.js
- lib/rest/client.js
Pass options along with key api calls. Also, was clobbering options in `createReadStream` and `createWriteStream`.
> Handle options / headers when opening streams.

- lib/fs/filesystem.js
This should allow the `X-Unique-ID` header to be passed along with upload and download requests.
> When creating a read or write stream, pass given headers.

- lib/rest/client.js
- tests/test_rest.js
Task errors are objects. This change formats them properly so that they are made into strings rather than `[object Object]`: https://sentry.lumanox.io/organizations/lumanox/issues/37126/events/e79e564c3d1e4bf0a92d5c783ca8f45d/?project=24&statsPeriod=14d
> Properly print task errors

- lib/fs/filesystem.js
- lib/rest/client.js
We use the request path in the library, since that is the only attribute we use, attach that instead.
Otherwise, the request object holds many resources, and because we return the error object, we cannot control it's lifetime.
> Don't attach heavyweight request object to error.

- lib/rest/client.js
- tests/test_fs.js
Parses the error message details when `Content-Type` is `application/json` to use for the callback error
```
ftp> get Makefile
local: Makefile remote: Makefile
200 OK
150 Opening ASCII data connection
426 Connection closed; transfer aborted. [0A0A0019:8020_AC1F0EFC:0015_63065DAE_00F5:0011:06287AD0CD54] Too many concurrent user connections. Upgrade to allow more.
```
> Download error message

- lib/rest/client.js
- tests/test_auth.js
The user may not want to fetch the user details and may want the results from the session API. The `whoami` method can be called specifically if desired
> Remove required call to whoami

- lib/fs/filesystem.js
This is a small change to allow for efficient implementation of MLSD and MLST.
Currently, when you make a `readdirstats()` call, only the children of the given path are returned. This PR adds a 3rd parameter to the callback which provides the stat info for the given path itself.
This change allows all FTP listing commands (STAT, LIST, MLST, MLSD) to call `readdirstats()`, otherwise a separate `stat()` call would be necessary (even though the data is available in `readdirstats()` but is discarded).
> Return parent directory info from readdirstats.
