Makefile
package-lock.json
package.json

Oops. I forgot to make a new branch. I recycled this one.
I added coverage using `nyc` and removed `istanbul`.

Added coverage.

---

index.js

More flattening.

---

lib/fs/fileproxy.js
lib/fs/filesystem.js
lib/fs/index.js
lib/index.js
lib/rest/basic.js
lib/rest/client.js
lib/rest/index.js
package-lock.json
package.json

Added metrics to the library. Some formatting changes. Set up logger to use simple output (instead of JSON).

Logging & Metrics

---

lib/rest/client.js
tests/test_rest.js

Fixes: https://github.com/smartfile/client-node/issues/21

Better error detection.

---

lib/rest/client.js

This was causing failures in `ftpserver` which were VERY hard to track down.

Safe statuscode

---

lib/fs/fileproxy.js
lib/fs/filesystem.js
tests/test_fs.js

Fixed several problems with `readFile()` and `writeFile()`. Included tests that triggered the bugs.

Fix readFile and writeFile with tests.

---

lib/fs/filesystem.js

I apparently copy / pasted some code and forgot to modify the parameter value to suit.
Closes https://github.com/smartfile/client-node/issues/28

Fix some incorrect opNames in metrics.

---

tests/test_rest.js

I added a test for this (for good measure) and it passes.

Add test for non-ascii mkdir.

---

lib/fs/filesystem.js
lib/rest/client.js
tests/test_fs.js

Closes https://github.com/smartfile/client-node/issues/42

Read offset

---

lib/rest/client.js

Problem with error handling I added this morning.

Checked the wrong var.

---

lib/fs/filesystem.js
tests/test_fs.js

Closes https://github.com/smartfile/client-node/issues/54

Add negative cache.

---

lib/fs/filesystem.js

Emits 'finish' when API callback is invoked.

Closes https://github.com/smartfile/client-node/issues/63

---

lib/rest/client.js

Sorry, felt I should move this comment when I reviewed my changes.

Move comment.

---

lib/keys.js

I am having trouble with the KeyFS cache in SFTP. Sometimes newly uploaded keys are not immediately available.
This caching strategy more closely resembles the one used in the FileSystem class.

Cache keys less aggresively.

---

lib/rest/client.js
package.json
tests/test_rest.js

Add interface to access the right API

Right API interface

---

lib/rest/client.js
tests/test_auth.js

Modify test to match actual API return. Fix client to handle empty reply.

API does not return any content.

---

.travis.yml
package-lock.json

Upgrade to npm 7

---

lib/fs/fileproxy.js
lib/fs/filesystem.js
lib/index.js
lib/keys.js
lib/rest/client.js
lib/rest/index.js
tests/test_auth.js
tests/test_fs.js
tests/test_keys.js
tests/test_rest.js

Sets the current defined logger as the default and allows for overriding it with another logger.

Allow for overriding the logger

---

lib/fs/fileproxy.js
lib/fs/filesystem.js

fs methods don't accept or handle options (and thus request headers).

Accept options in fs interface.

---

lib/rest/client.js

Keeps track of authenticated status to prevent attempts to log out when not authenticated or when already logged out

Only log out if authenticated

---

lib/rest/client.js
tests/test_fs.js

Parses the error message details if they exist to use for the callback error

Parse message in error responses

---

package-lock.json
package.json
tests/test_fs.js

Upgrades the client to better integrate with newer projects

Upgrade prometheus client
